import assert from 'node:assert/strict'
import {
  SIMULATION_ROUND_LIMITS,
  calculateAutoGeneratedRounds,
  calculateSliderPercent,
  getDefaultRecommendedRounds,
  normalizeCustomRounds
} from '../src/utils/simulationRounds.js'

assert.deepEqual(SIMULATION_ROUND_LIMITS, {
  min: 8,
  max: 72,
  step: 8,
  recommended: 24,
  minutesPerRound: 60,
  totalSimulationHours: 72
})

assert.equal(normalizeCustomRounds(undefined), 24)
assert.equal(normalizeCustomRounds(1), 8)
assert.equal(normalizeCustomRounds(72), 72)
assert.equal(normalizeCustomRounds(999), 72)
assert.equal(normalizeCustomRounds(25), 24)
assert.equal(normalizeCustomRounds(29), 32)

assert.equal(calculateAutoGeneratedRounds({
  total_simulation_hours: 72,
  minutes_per_round: 60
}), 72)

assert.equal(calculateAutoGeneratedRounds({
  total_simulation_hours: 168,
  minutes_per_round: 60
}), 72)

assert.equal(calculateSliderPercent(24), 25)
assert.equal(getDefaultRecommendedRounds(), 24)

console.log('simulationRounds tests passed')
