export const SIMULATION_ROUND_LIMITS = Object.freeze({
  min: 8,
  max: 72,
  step: 8,
  recommended: 24,
  minutesPerRound: 60,
  totalSimulationHours: 72
})

export const normalizeCustomRounds = (value) => {
  const numeric = Number(value)
  if (!Number.isFinite(numeric)) return SIMULATION_ROUND_LIMITS.recommended

  const clamped = Math.min(
    SIMULATION_ROUND_LIMITS.max,
    Math.max(SIMULATION_ROUND_LIMITS.min, numeric)
  )
  const steps = Math.round((clamped - SIMULATION_ROUND_LIMITS.min) / SIMULATION_ROUND_LIMITS.step)
  return SIMULATION_ROUND_LIMITS.min + steps * SIMULATION_ROUND_LIMITS.step
}

export const calculateAutoGeneratedRounds = (timeConfig = {}) => {
  const totalHours = Number(timeConfig.total_simulation_hours)
  const minutesPerRound = Number(timeConfig.minutes_per_round)
  if (!Number.isFinite(totalHours) || totalHours <= 0 || !Number.isFinite(minutesPerRound) || minutesPerRound <= 0) {
    return null
  }

  return Math.min(
    SIMULATION_ROUND_LIMITS.max,
    Math.floor((totalHours * 60) / minutesPerRound)
  )
}

export const calculateSliderPercent = (rounds) => {
  const normalized = normalizeCustomRounds(rounds)
  return ((normalized - SIMULATION_ROUND_LIMITS.min) /
    (SIMULATION_ROUND_LIMITS.max - SIMULATION_ROUND_LIMITS.min)) * 100
}

export const getDefaultRecommendedRounds = () => SIMULATION_ROUND_LIMITS.recommended
